config/routes.rb
Rails.application.routes.draw do
  
  root to: 'toppages#index'

  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  get 'signup', to: 'users#new'
  resources :users, only: [:show, :create]
 
  resources :reviews
  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :review
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :user
  
  validates :title, presence: true, length: { maximum: 50 }
  validates :text, presence: true, length: { maximum: 500 }
  
  has_many :favorites
  has_many :users, through: :favorites
  
  
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email.downcase! }
  validates :name, presence: true, length: { maximum: 50}
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  
  has_many :reviews
  has_many :favorites
  has_many :likes, through: :favorites, source: :review
  
  def favorite(review)
    self.favorites.find_or_create_by(review_id: review.id)
  end

  def unfavorite(review)
    favorite = self.favorites.find_by(review_id: review.id)
    favorite.destroy if favorite
  end

  def likes?(review)
   self.likes.include?(review)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper  #追記
  include Pagy::Backend
  
  private

  def require_user_logged_in
    unless logged_in?
      redirect_to login_url
    end
  end
  
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
before_action :require_user_logged_in

  def create
    review = Review.find(params[:review_id])
    current_user.favorite(review)
    flash[:success] = 'お気に入りしました。'
    redirect_back(fallback_location: root_path)
  end
  

  def destroy
    review = Review.find(params[:review_id])
    current_user.unfavorite(review)
    flash[:success] = 'お気に入りを解除しました。'
    redirect_back(fallback_location: root_path)
  end
 
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :require_user_logged_in
  before_action :set_review, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :destroy]
    
  def index
    @reviews = Review.all
  end

  def show
    # @review = Review.find(params[:id])
  end

  def new
     @review = Review.new
  end

  def create
      @review = current_user.reviews.build(review_params)
      # @review = Review.new(review_params)
    if @review.save
      flash[:success] = 'レビューが正常に投稿されました'
      redirect_to @review
    else
      flash.now[:danger] = 'レビューが投稿されませんでした'
      render :new
    end
  end

  def edit
    # @review = Review.find(params[:id])
  end

  def update
    # @review = Review.find(params[:id])
    if @review.update(review_params)
      flash[:success] = 'レビューは正常に更新されました'
      redirect_to @review
    else
      flash.now[:danger] = 'レビューは更新されませんでした'
      render :edit
    end
  end

  def destroy
    # @review = Review.find(params[:id])
    @review.destroy
    flash[:success] = 'レビューは正常に削除されました'
    redirect_to reviews_url
  end
  
private

  # Strong Parameter
  def set_review
    @review = Review.find(params[:id])
  end
  
  def review_params
    params.require(:review).permit(:title, :text)
  end
  
  def correct_user
    @review = current_user.reviews.find_by(id: params[:id])
    unless @review
      redirect_to root_url
    end
  end 
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    email = params[:session][:email].downcase
    password = params[:session][:password]
    if login(email, password)
      flash[:success] = 'ログインに成功しました。'
      redirect_to reviews_path
    else
      flash.now[:danger] = 'ログインに失敗しました。'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:success] = 'ログアウトしました。'
    redirect_to root_url
  end
  
  private

  def login(email, password)
    @user = User.find_by(email: email)
    if @user && @user.authenticate(password)
      # ログイン成功
      session[:user_id] = @user.id
      return true
    else
      # ログイン失敗
      return false
    end
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
     if logged_in?
      @review = current_user.reviews.build  # form_with 用
      @pagy, @reviews = pagy(current_user.reviews.order(id: :desc))
     end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_user_logged_in, only: [:show]
  
  # def index
  #   @pagy, @users = pagy(User.order(id: :desc), items: 20)
  # end

  def show
    @user = User.find(params[:id])
  end

  def new
    @user = User.new
  end

  def create
     @user = User.new(user_params)

    if @user.save
      flash[:success] = 'ユーザを登録しました。'
      redirect_to @user
    else
      flash.now[:danger] = 'ユーザの登録に失敗しました。'
      render :new
    end
    
    def likes
    @user = User.find(params[:id])
    @likes = @user.likes
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  include Pagy::Frontend
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !!current_user
  end
  
end

app/views/favorites/_favorite_button.html.erb
<% if current_user.likes?(review) %>
  <%= form_with(model: current_user.favorites.find_by(review_id: review.id), method: :delete) do |f| %>
     <%= hidden_field_tag :review_id, review.id %>
     <%= f.submit 'Unfavorite', class: 'btn btn-danger btn-sm' %>
   <% end %>

<% else %>

  <%= form_with(model: current_user.favorites.build) do |f| %>
  <%= hidden_field_tag :review_id, review.id %>
  <%= f.submit 'Favorite',  class: 'btn btn-primary btn-sm' %>
  <% end %>
  
<% end %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div id="error_explanation" class="alert alert-warning">
    <ul class="mb-0">
      <% model.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/_flash_messages.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_navbar.html.erb
<header class="mb-4">
  <nav class="navbar navbar-expand-sm navbar-dark bg-secondary">
    <div class="container-fluid ps-5 pe-5">
      <a class="navbar-brand">SomeReview</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent">
        <span class="navbar-toggler-icon"></span>
      </button>

      <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">

 <% if logged_in? %>
    <div class="btn-group">
      <ul class="navbar-nav">
         <li class="ms-3"><%= link_to 'レビュー一覧', reviews_path, class: 'nav-link' %></li>
      </ul>
         <ul class="navbar-nav">
             <li class="ms-3"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
      </ul>
    </div>
  <% else %>
  
  <ul class="navbar-nav">
          <li class="nav-item"><%= link_to 'ログイン', login_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'ログアウト', logout_path, method: :delete, class: 'nav-link' %></li>
        </ul>
  <% end %>      
      </div>
    </div>
  </nav>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>Some Reviews</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"></script>
  </head>
  

  <body data-turbolinks="false">
    
    <div class="main-container">
    <%= render 'layouts/navbar' %>
    
    <div class="container">
    <%= render 'layouts/flash_messages' %>
    <%= yield %>
    </div>
  </div>
  </body>

</html>

app/views/reviews/_form.html.erb
<%= form_with(model: review ) do |f| %>
  <%= f.label :title, 'タイトル' %>
  <%= f.text_field :title, class: 'form-control' %>
  
  <%= f.label :text, 'レビュー' %>
  <%= f.text_area :text, class: 'form-control', size: "70*70" %>

<div class="row m-4">
  <div class="mx-auto" style="width: 200px;">
  <div class="col-sm-10 pb-4">
    <%= f.submit '投稿', class: 'align-items-center, btn btn-secondary btn-sm mr-6' %>
    <%= link_to '一覧に戻る', reviews_path, class: 'align-items-center, btn btn-secondary btn-sm mr-6' %>
  </div>
  </div>
</div>
<% end %>

app/views/reviews/edit.html.erb
<h1 class="text-center">id: <%= @review.id %> 編集ページ</h1>

<%= form_with(model: @review) do |f| %>
<%= render 'form', review: @review %>

<% end %>

app/views/reviews/index.html.erb
<h1 class="text-center">レビュー一覧</h1>
 
<div class="container">
   <div class="row align-items-center">
  <ul>
    <table class="table table-bordered table-light">
      <tr>
        <th class="text-center table-secondary align-middle" style="width: 5%">id</th>
        <th class="text-center table-secondary align-middle" style="width: 30%">タイトル</th>
        <th class="text-center table-secondary align-middle" style="width: 55%">レビュー</th>
        <th class="text-center table-secondary align-middle" style="width: 10%">お気に入り</th>
      </tr>

  <% @reviews.each do |review| %>
      <tr>
        <th class="text-center align-middle"><%= link_to review.id, review %></th> 
        <th class="text-left align-middle"><%= review.title %></th>
        <th class="text-left align-middle"><%= review.text %></th>
        <th class="text-center align-middle"><%= render 'favorites/favorite_button', review: review %></th>
      </tr>
  <% end %>
   </table>
   </ul>
  </div>  
</div>   
   
<div class="mx-auto" style="width: 200px;">
<%= link_to '新規レビュー投稿', new_review_path, class: 'align-items-center, btn btn-secondary btn-sm mr-6' %>
</div>

app/views/reviews/new.html.erb
<h1 class="text-center">新規レビュー</h1>

<%= render 'form', review: @review %>

<!--< %= link_to '一覧に戻る', reviews_path %>-->

app/views/reviews/show.html.erb
<h1 class="text-center">id: <%= @review.id %></h1>

<ul>
     <table class="table table-bordered table-light">
     <tr>
       <th class="text-center table-secondary align-middle"  style="width: 35%">タイトル</th>
       <th class="text-center table-secondary align-middle"  style="width: 60%">レビュー</th>
      <!--<th class="text-center table-secondary align-middle"  style="width: 5%">お気に入り</th>-->
     </tr>
     <tr>
       <th class="text-center align-middle"><%= @review.title %></th>
       <th class="text-left align-middle"><%= @review.text %></th>
        <!--<th class="text-center align-middle">< %= render 'favorites/favorite_button', review: @review %></th>-->
    </tr>
    </table>
</ul> 
<div class="row">
  <div class="mx-auto" style="width: 600px;">
  <div class="col-sm-10 offset-sm-3">
  <%= link_to '一覧に戻る', reviews_path, class: 'btn btn-secondary btn-sm mr-6' %>
  <%= link_to 'このレビューを編集する', edit_review_path(@review), class: 'btn btn-secondary btn-sm mr-6' %>
  <%= link_to 'このレビューを削除する', @review, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: 'btn btn-danger btn-sm'  %>
</div>
</div>
</div>

app/views/toppages/index.html.erb
<% if logged_in? %>
  <!--<p>ログイン完了ユーザ: < %= current_user.name %></p>-->
 <% redirect_to root_path %>

<% else %>
　<!--<div class="main-container">-->
　  <div class="bg-secondary p-3 p-sm-5 my-4 rounded">
    <div class="text-center text-white">
      <h1>Some Review</h1>
    </div>
  </div>

  <div>
    <div class="text-center p-5">
      <%= link_to 'Sign up!', signup_path, class: 'btn btn-lg btn-primary'  %>
  </div>
  </div>
  
  <div class="bg-white rounded">
    <div class="text-center text-black border">
    <p class="text-justify">注意事項<br>
    ・「ネタバレ」を含みます<br>
    ・感想は個人の主観です</p>
 </div>
 </div>
  <!--</div>-->
<% end %>

app/views/users/new.html.erb
<!--<h1>Users#new</h1>-->
<!--<p>Find me in app/views/users/new.html.erb</p>-->
<div class="text-center">
  <h1>Sign up</h1>
</div>

<div class="row">
  <div class="col-sm-6 offset-sm-3">

    <%= form_with(model: @user) do |f| %>
      <%= render 'layouts/error_messages', model: f.object %>

      <div class="mb-3">
        <%= f.label :name, 'Name' %>
        <%= f.text_field :name, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :email, 'Email' %>
        <%= f.email_field :email, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password, 'Password' %>
        <%= f.password_field :password, class: 'form-control' %>
      </div>

      <div class="mb-3">
        <%= f.label :password_confirmation, 'Confirmation' %>
        <%= f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <%= f.submit 'Sign up', class: 'btn btn-primary w-100' %>
    <% end %>
  </div>
</div>